# Generated by Django 5.2.1 on 2025-05-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationsite',
            name='selector_goal',
            field=models.CharField(blank=True, default='', help_text='CSS selector to extract the goal amount', max_length=200),
        ),
        migrations.AddField(
            model_name='donationsite',
            name='selector_image',
            field=models.CharField(blank=True, default='', help_text='CSS selector to extract image URL', max_length=200),
        ),
        migrations.AddField(
            model_name='donationsite',
            name='selector_name',
            field=models.CharField(blank=True, default='', help_text='CSS selector to extract campaign name', max_length=200),
        ),
        migrations.AddField(
            model_name='donationsite',
            name='selector_saved',
            field=models.CharField(blank=True, default='', help_text='CSS selector to extract the saved amount', max_length=200),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='external_url',
            field=models.URLField(help_text='Original donation page URL'),
        ),
    ]
