# Generated by Django 5.2.1 on 2025-05-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_donationsite_selector_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationsite',
            name='use_selenium',
            field=models.BooleanField(default=False, help_text='Use Selenium instead of requests/BeautifulSoup'),
        ),
    ]
