# Generated by Django 5.2.1 on 2025-05-26 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_donationsite_use_selenium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationsite',
            name='use_selenium',
        ),
    ]
