# Generated by Django 5.2.8 on 2025-11-22 21:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_remove_donationsite_use_selenium'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('saved', models.BigIntegerField()),
                ('goal', models.BigIntegerField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='campaigns.campaign')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['campaign', 'timestamp'], name='campaigns_c_campaig_ef063f_idx')],
            },
        ),
    ]
